owner: hackebein
repo: vpmm-upptime

sites:
  - name: "[LIVE] VPMM Frontend"
    url: https://vpmm.dev
    maxResponseTime: 100
    expectedStatusCodes:
      - 200
  - name: "[LIVE] VPM Index"
    url: https://vpmm.dev/index.json
    maxResponseTime: 500
    expectedStatusCodes:
      - 200
  - name: "[LIVE] VPMM Index"
    url: https://vpmm.dev/vpmm.json
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: "[STAGING] VPMM Frontend"
    url: https://staging.vpmm.dev
    maxResponseTime: 100
    expectedStatusCodes:
      - 200
  - name: "[STAGING] VPM Index"
    url: https://staging.vpmm.dev/index.json
    maxResponseTime: 500
    expectedStatusCodes:
      - 200
  - name: "[STAGING] VPMM Index"
    url: https://staging.vpmm.dev/vpmm.json
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200

status-website:
  cname: status.vpmm.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VPMM Uptime
  theme: night
  introTitle: VPMM Uptime
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: "[LIVE] VPMM"
      href: https://vpmm.dev
    - title: "[STAGING] VPMM"
      href: https://staging.vpmm.dev

workflowSchedule:
  graphs: "2/5 * * * *"
  responseTime: "1/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0/5 * * * *"